### ISSUE TITLE
periodic recording support

### ISSUE THREAD

**Issue by sho-saito** [aws-samples/aws-control-tower-config-customization#11]
Hi,

https://aws.amazon.com/about-aws/whats-new/2023/11/aws-config-periodic-recording/ 
After the update mentioned in this post, AWS Config supports new recording frequency option of DAILY.
This will help AWS users reduce the recording cost of AWS Config.

So I hope this will be supported in this customization solution.

Thank you.

**Comment by drem-darios** [comment]
One suggestion I have to this change is to also take in a new parameter called `CONFIG_RECORDER_DAILY_RESOURCE_LIST` so users can set _some_ resources to be daily if desired. Then you can use this list to set daily overrides: `'recordingModeOverrides': [
                                {
                                    'description': 'DAILY_OVERRIDE',
                                    'resourceTypes': CONFIG_RECORDER_DAILY_RESOURCE_LIST,
                                    'recordingFrequency': 'DAILY'
                                }
                            ]`

This allows users to have three options: exclude one or more resource, set the recording frequency for one or more resources to daily, and set all resources to continuous or daily recording.

**Comment by priiiiit** [comment]
This was implemented with #13 can be marked as done now?
